[package]
name = "orinium_browser"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace]
resolver = "3"

[dependencies]
dhat = "0.3.3"

# orinium_text = { path = "../orinium_text" }
orinium_text = {
  git = "https://github.com/orinium-browser/orinium_text",
  rev = "53ed52fb807919a07a6516e05dd6b9c3d81039bb",
}

ab_glyph = "0.2"
anyhow = "1.0"
bytemuck = { version = "1.25", features = ["derive"] }
cpal = "0.18.1"
entities = "1.0.1"
env_logger = "0.11.10"
etagere = "0.3.0"
fontdue = "0.9.3"
http-body-util = "0.1"
hyper = { version = "1", features = ["client", "http1", "http2"] }
hyper-util = { version = "0.1", features = ["tokio"] }
image = "0.25.10"
ipc-channel = "0.22.0"
log = "0.4.32"
once_cell = "1.21.4"
pixi_byte = {
  git = "https://github.com/orinium-browser/pixi_byte",
  branch = "dev"
}
pollster = "0.4"
rustls = { version = "0.23.40", default-features = false, features = ["tls12"] }
rustls-native-certs = "0.8.4"
serde = "1.0.228"
smol_str = "0.3.6"
symphonia = {
  version = "0.6.0",
  features = ["aac", "flac", "mp3", "vorbis", "wav"]
}
tokio = { version = "1.52", features = ["fs", "io-std", "net", "rt", "time"] }
tokio-rustls = "0.26.4"
ui_layout = {
  git = "https://github.com/098orin/ui_layout-rs",
  rev = "369a67e0a7ce00e51422a164f458f26101165aa3"
}
url = "2.5"
wgpu = "29.0.1"
wgpu-types = "29.0.1"
winit = "0.30.13"

[dev-dependencies]
colored = "3.1.1"  # コマンドラインハイライト用
strsim = "0.11.1"

[features]
dhat-heap = []
