[package]
name = "orinium_browser"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace]
resolver = "3"

[dependencies]
dhat = "0.3.3"

# orinium_text = { path = "../orinium_text" }
orinium_text = {
  git = "https://github.com/orinium-browser/orinium_text",
  rev = "6501dac12b2091dd6cc6bbca6139294d0fa08bd6",
}

ab_glyph = "0.2"
anyhow = "1.0"
bytemuck = { version = "1.25", features = ["derive"] }
cpal = "0.18.1"
entities = "1.0.1"
env_logger = "0.11.10"
etagere = "0.3.0"
fontdue = "0.9.3"
http-body-util = "0.1"
hyper = { version = "1", features = ["client", "http1", "http2"] }
hyper-util = { version = "0.1", features = ["tokio"] }
image = "0.25.10"
ipc-channel = "0.22.0"
log = "0.4.32"
lru = "0.18"
once_cell = "1.21.4"
pixi_byte = {
  git = "https://github.com/orinium-browser/pixi_byte",
  rev = "9de1b545f412b33d864bb65896ec65d12509865e"
}
pollster = "1.0"
rustls = { version = "0.23.40", default-features = false, features = ["tls12"] }
rustls-native-certs = "0.8.4"
serde = { version = "1", features = ["derive"] }
smol_str = "0.3.6"
symphonia = {
  version = "0.6.0",
  features = ["aac", "flac", "mp3", "vorbis", "wav"]
}
tokio = { version = "1.52", features = ["fs", "io-std", "net", "rt", "time"] }
tokio-rustls = "0.26.4"
ui_layout = {
  git = "https://github.com/098orin/ui_layout-rs",
  rev = "c272095d2c85550474607461f46a41d9945d6e90"
}
url = "2.5"
wgpu = "30.0.0"
wgpu-types = "30.0.0"
winit = "0.30.13"

[dev-dependencies]
colored = "3.1.1"  # コマンドラインハイライト用
strsim = "0.11.1"

[features]
dhat-heap = []
